<?php

  // CONFIG

  // Admin config (WIP coming soon):
  //$admin_interface = true;
  //$admin_username = "";
  //$admin_password = "";
  $admin_mail = "blocus-org@proton.me"; // For privacy policy contact, change it to match yours

  // Database config:
  $hostname = "localhost";
  $username = "";
  $password = "";
  $dbname = "blocus_chat_db";

  // Footer config:
  $app_name = "Blocus-chatroom";
  $app_version = "beta-2.0.0";
  $source_url = ""; // Only if source code has been modified

  // Encryption key:
  $encryption_key = ")J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVk"; // Change it to another autogenerated SHA256 key

  // END

  // FUNCTIONS

  // Set link to source code
  if($source_url != ""){
    $source_code = $source_url;
  }else{
    $source_code = "https://github.com/Blocus-org/blocus-chatroom";
  }

  // Database connection and errors displaying
  $conn = mysqli_connect($hostname, $username, $password, $dbname);
  if(!$conn){
    echo "Database connection error".mysqli_connect_error();
  }

  // Special chars escaping
  function sec($data){
    $data = trim($data);
    $data = stripslashes($data);  
    $data = strip_tags($data);
    return $data;
  }

  // END
?>

